services:
  mongodb:
    image: mongo:latest
    container_name: anamcon_db
    ports:
      - "27017:27017"
    networks:
      - anamcon_net

  web_app:
    build:
      context: ./src/web_app
    ports:
      - "5000:5000"
    networks:
      - anamcon_net
    depends_on:
      - mongodb

networks:
  anamcon_net: