# -------------------------------
# This file is part of AnamCon
# by David Brau Queralt
# -------------------------------


USE_AVAILABLE_LANGUAGES=['es', 'en']
USE_AVAILABLE_LANGUAGES_VERBOSE=[['Español', '(España)'], ['English', '(USA)']]
USE_AVAILABLE_ANAMNESIS_MODES=['general', 'psico']
USE_AVAILABLE_ANAMNESIS_MODES_ICONS=['🗣️ ', '🧠']
USE_ANAMNESIS_TEXTS_ES={'language': 'es', 'title': 'AnamCon - Anamnesis', 'navigator_menu_title': 'ANAMNESIS', 'reports_menu_title': 'INFORMES', 'user_menu_title': 'USUARIO', 'log_out_menu_title': 'SALIR', 'navigation_zone': 'Navegador', 'anamnesis_zone': 'Anamnesis', 'summary_zone': 'Resumen', 'anamnesis_title': 'Título', 'new_anamnesis': 'Nueva anamnesis', 'input_placeholder': 'Escribe aquí tu mensaje', 'available_anamnesis_icons': ['🗣️ ', '🧠'], 'available_anamnesis_names': ['general', 'psico'], 'available_anamnesis_texts': ['General', 'Psicológica'], 'delete_confirm_text': '¿Estás seguro que deseas eliminar esta anamnesis?', 'no_navigation_icon_text': '🛈', 'no_navigation_main_text': 'Ninguna anamnesis por aquí.', 'start_anamnesis_text_1': '¡Importante!', 'start_anamnesis_text_2': 'Antes de continuar, por favor, dedique un momento a revisar las condiciones de uso:', 'start_anamnesis_text_3_1': 'Uso con fines académicos.', 'start_anamnesis_text_3_2': 'No para uso médico.', 'start_anamnesis_text_4': 'Tiempo total de anamnesis ilimitado.', 'start_anamnesis_text_5_1': 'Tiempo', 'start_anamnesis_text_5_2': 'máximo entre interacciones 20 minutos.', 'start_anamnesis_text_6': 'Puede cancelar cualquier interacción indicando que "ha habido un error".', 'start_anamnesis_text_7': 'Informe inmediato tras finalizar la anamnesis.', 'start_anamnesis_text_8': 'Analíticas de uso tras finalizar la anamnesis.', 'start_anamnesis_text_9': 'Al continuar acepta todos los términos y condiciones de uso.', 'no_anamnesis_icon_text': '🛈', 'no_anamnesis_main_text': 'Debe seleccionar una anamnesis', 'no_symptoms_text': 'Ningún síntoma', 'no_anamnesis_data_text': 'Datos no disponibles.', 'download_report_button_text': 'Descargar informe', 'summary_title_text_1': 'Regiones sintomáticas', 'summary_title_text_2': 'Síntomas guía', 'summary_title_text_3': 'Datos de la anamnesis', 'summary_data_type_text': 'Tipo', 'summary_data_state_text': 'Estado', 'summary_data__duration_text': 'Duración', 'summary_data_creation_datetime_text': 'Creación', 'summary_data_last_interaction_datetime_text': 'Última interacción', 'summary_data_num_interactions_text': 'Número interacciones', 'disclaimer': 'No destinado para uso médico', 'copyright': 'Copyright © 2023 AnamCon', 'version': 'Versión 0.1', 'terms': 'Términos'}
USE_ANAMNESIS_TEXTS_EN={'language': 'en', 'title': 'AnamCon - Anamnesis', 'navigator_menu_title': 'ANAMNESIS', 'reports_menu_title': 'REPORTS', 'user_menu_title': 'USER', 'log_out_menu_title': 'LOG OUT', 'navigation_zone': 'Navigator', 'anamnesis_zone': 'Anamnesis', 'summary_zone': 'Summary', 'anamnesis_title': 'Title', 'new_anamnesis': 'New anamnesis', 'input_placeholder': 'Type your message here', 'available_anamnesis_icons': ['🗣️ ', '🧠'], 'available_anamnesis_names': ['general', 'psico'], 'available_anamnesis_texts': ['General', 'Psychological'], 'delete_confirm_text': 'Are you sure you want to delete this medical history?', 'no_navigation_icon_text': '🛈', 'no_navigation_main_text': 'No medical history around here.', 'start_anamnesis_text_1': 'Important!', 'start_anamnesis_text_2': 'Before proceeding, please take a moment to review the terms of use:', 'start_anamnesis_text_3_1': 'For academic purposes.', 'start_anamnesis_text_3_2': 'Not for medical use.', 'start_anamnesis_text_4': 'Total time for medical history is unlimited.', 'start_anamnesis_text_5_1': 'Time', 'start_anamnesis_text_5_2': 'maximum between interactions is 20 minutes.', 'start_anamnesis_text_6': 'You can cancel any interaction by indicating "there has been an error".', 'start_anamnesis_text_7': 'Immediate report upon completion of medical history.', 'start_anamnesis_text_8': 'Usage analytics upon completion of medical history.', 'start_anamnesis_text_9': 'By continuing, you accept all terms and conditions of use.', 'no_anamnesis_icon_text': '🛈', 'no_anamnesis_main_text': 'You must select a medical history.', 'no_symptoms_text': 'No symptoms', 'no_anamnesis_data_text': 'Data not available.', 'download_report_button_text': 'Download report', 'summary_title_text_1': 'Symptomatic regions', 'summary_title_text_2': 'Guide symptoms', 'summary_title_text_3': 'Medical history data', 'summary_data_type_text': 'Type', 'summary_data_state_text': 'State', 'summary_data__duration_text': 'Duration', 'summary_data_creation_datetime_text': 'Creation', 'summary_data_last_interaction_datetime_text': 'Last interaction', 'summary_data_num_interactions_text': 'Number of interactions', 'disclaimer': 'Not intended for medical use', 'copyright': 'Copyright © 2023 AnamCon', 'version': 'Version 0.1', 'terms': 'Terms'}
